server:
  port: 8084
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myspringdata
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org.springframework.web: DEBUG
    ma.PFE.local: DEBUG
    org.hibernate: ERROR